web/router.ex
defmodule Chat.Router do
  use Chat.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Chat.Auth, repo: Chat.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Chat do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/users", UserController, only: [:create, :new]
    resources "/sessions", SessionController, only: [:create, :new, :delete]
  end

  # Other scopes may use custom stacks.
  # scope "/api", Chat do
  #   pipe_through :api
  # end
end

lib/chat/endpoint.ex
defmodule Chat.Endpoint do
  use Phoenix.Endpoint, otp_app: :chat

  socket "/socket", Chat.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :chat, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_chat_key",
    signing_salt: "hmOeht89"

  plug Chat.Router
end

lib/chat/repo.ex
defmodule Chat.Repo do
  use Ecto.Repo, otp_app: :chat
end

web/models/message.ex
defmodule Chat.Message do
	use Chat.Web, :model

	schema "messages" do
		field :body, :string
		field :at, :string
		belongs_to :user, Chat.User
		belongs_to :room, Chat.Room
	end


	def changeset(model, params \\ %{}) do
    model
  end
end

web/models/room.ex
defmodule Chat.Room do
	use Chat.Web, :model

	schema "rooms" do
		field :name, :string
		field :user_ids, {:array, :integer}

		timestamps
	end
end

web/models/user.ex
defmodule Chat.User do
	use Chat.Web, :model

	schema "users" do
		field :username, :string
		field :password, :string, virtual: true
		field :password_hash, :string

		timestamps
	end

	def changeset(model, params \\ %{}) do
		model
		|> cast(params, ~w(username), [])
		|> validate_length(:username, min: 3, max: 20)
		|> unique_constraint(:username)
	end

	def registration_changeset(model, params) do
		model
		|> changeset(params)
		|> cast(params, ~w(password), [])
		|> validate_length(:password, min: 3, max: 100)
		|> put_password_hash()
	end

	defp put_password_hash(changeset) do
		case changeset do
			%Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
				put_change(changeset, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
			_ ->
				changeset
		end
	end
end

web/controllers/page_controller.ex
defmodule Chat.PageController do
  use Chat.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/session_controller.ex
defmodule Chat.SessionController do
	use Chat.Web, :controller

	def new(conn, _) do
		render conn, "new.html"
	end

	def create(conn, %{"session" => %{"username" => user, "password" => pass}}) do
		case Chat.Auth.login_by_username_and_pass(conn, user, pass, repo: Repo) do
			{:ok, conn} ->
				conn
				|> redirect(to: page_path(conn, :index))
			{:error, _reason, conn} ->
				conn
				|> put_flash(:error, "Invalid username/password")
				|> render("new.html")
		end
	end

	def delete(conn, _) do
		conn
		|> Chat.Auth.logout()
		|> redirect(to: page_path(conn, :index))
	end
end

web/controllers/user_controller.ex
defmodule Chat.UserController do
	use Chat.Web, :controller
	alias Chat.User

	def new(conn, _params) do
		changeset = User.changeset(%User{})
		render conn, "new.html", changeset: changeset
	end

	def create(conn, %{"user" => user_params}) do
		changeset = User.registration_changeset(%User{}, user_params)

		case Repo.insert(changeset) do
			{:ok, user} ->
				conn
				|> Chat.Auth.login(user)
				|> redirect(to: page_path(conn, :index))
			{:error, changeset} ->
				render(conn, "new.html", changeset: changeset)
		end
	end
end

web/views/error_view.ex
defmodule Chat.ErrorView do
  use Chat.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Chat.LayoutView do
  use Chat.Web, :view
end

web/views/message_view.ex
defmodule Chat.MessageView do
	use Chat.Web, :view

	def render("messages.json", %{message: msg}) do
		%{
			id: msg.id,
			body: msg.body,
			username: msg.user.username,
			at: msg.at
		}
	end
end

web/views/page_view.ex
defmodule Chat.PageView do
  use Chat.Web, :view
end

web/views/session_view.ex
defmodule Chat.SessionView do
	use Chat.Web, :view
end

web/views/user_view.ex
defmodule Chat.UserView do
	use Chat.Web, :view

	def render("user.json", %{user: user}) do
		%{id: user.id, username: user.username}
	end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Chat!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <%= render @view_module, @view_template, assigns %>

    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.3/moment.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.min.js"></script>
    <script>window.userToken = "<%= assigns[:user_token] %>"</script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<section class="content col-lg-2">
  <ol class="breadcrumb text-center">
    <%= if @current_user do %>
      <li id="current-username"><%= @current_user.username %></li> (you)
      <li><%= link "Log out", to: session_path(@conn, :delete, @current_user), method: "delete" %></li>
    <% else %>
      <li><%= link "Register", to: user_path(@conn, :new) %></li>
      <li><%= link "Log in", to: session_path(@conn, :new) %></li>
    <% end %>
  </ol>
  Online:
  <div id="users_list"></div>
</section>
<section class="content col-lg-10">
  <div class="box box-success">
    <div class="box-header">
      <i class="fa fa-comments-o"></i>
      <h3 class="box-title">x</h3>
    </div>
    <div id="more">Show more</div>
    <div class="box-body chat" id="chat-box" style="overflow-y: scroll; height: 500px; resize: vertical;">
    </div>
    <div class="box-footer">
      <div class="col-sm-12">
        <div class="input-group">
          <input class="form-control" id="message" placeholder="Type message...">
          <div class="input-group-btn">
            <button type="button" class="btn btn-success" id="send-button">Send</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

web/templates/session/new.html.eex
<div class="container">
	<h1>Login</h1>

	<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
		<div class="form-group">
			<%= text_input f, :username, placeholder: "Username", class: "form-control" %>
		</div>
		<div class="form-group">
			<%= password_input f, :password, placeholder: "Password", class: "form-control" %>
		</div>
		<%= submit "Log in", class: "btn btn-primary" %>
	<% end %>
	<%= link "< Back", to: page_path(@conn, :index) %>
</div>

web/templates/user/new.html.eex
<%= if @changeset.action do %>
	<div class="alert alert-danger">
		<p>Oops, something went wrong!</p>
	</div>
<% end %>

<div class="container">
	<h1>Sign Up</h1>
	
	<%= form_for @changeset, user_path(@conn, :create), fn f -> %>
		<div class="form-group">
			<%= text_input f, :username, placeholder: "Username", class: "form-control" %>
			<%= error_tag f, :username %>
		</div>
		<div class="form-group">
			<%= password_input f, :password, placeholder: "Password", class: "form-control" %>
			<%= error_tag f, :password %>
		</div>
		<%= submit "Sign Up", class: "btn btn-primary" %>
	<% end %>
	<%= link "< Back", to: page_path(@conn, :index) %>
</div>